# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado/Vivado_Projects/Verilog Projects/lenet_stream/lenet_stream.srcs/sources_1/ip/activation_bram/activation_bram.xci
# IP: The module: 'activation_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/Vivado_Projects/Verilog Projects/lenet_stream/lenet_stream.srcs/sources_1/ip/activation_bram/activation_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'activation_bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Vivado/Vivado_Projects/Verilog Projects/lenet_stream/lenet_stream.srcs/sources_1/ip/activation_bram/activation_bram.xci
# IP: The module: 'activation_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/Vivado_Projects/Verilog Projects/lenet_stream/lenet_stream.srcs/sources_1/ip/activation_bram/activation_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'activation_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
