######################################################################
#
# File name : line_buf_conv_tb_wave.do
# Created on: Mon Apr 26 02:06:21 +0530 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
