######################################################################
#
# File name : line_buf_conv_tb_simulate.do
# Created on: Mon Apr 26 02:21:00 +0530 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L blk_mem_gen_v8_4_4 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.line_buf_conv_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {line_buf_conv_tb_wave.do}

view wave
view structure
view signals

log -r /*

do {line_buf_conv_tb.udo}

run 100000ns
