######################################################################
#
# File name : line_buf_conv_tb_compile.do
# Created on: Mon Apr 26 02:20:56 +0530 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/blk_mem_gen_v8_4_4
vlib modelsim_lib/msim/xil_defaultlib

vmap blk_mem_gen_v8_4_4 modelsim_lib/msim/blk_mem_gen_v8_4_4
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work blk_mem_gen_v8_4_4  "+incdir+../../../../lenet_stream.srcs/sources_1/imports/src" \
"../../../../lenet_stream.ip_user_files/ipstatic/simulation/blk_mem_gen_v8_4.v" \

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../lenet_stream.srcs/sources_1/imports/src" \
"../../../../lenet_stream.srcs/sources_1/ip/activation_bram/sim/activation_bram.v" \
"../../../../lenet_stream.srcs/sources_1/imports/src/accelerator_top.v" \
"../../../../lenet_stream.srcs/sources_1/imports/src/accumilator.v" \
"../../../../lenet_stream.srcs/sources_1/imports/src/addertree_25.v" \
"../../../../lenet_stream.srcs/sources_1/imports/src/conv1_bias.v" \
"../../../../lenet_stream.srcs/sources_1/imports/src/conv2_bias.v" \
"../../../../lenet_stream.srcs/sources_1/imports/src/conv3_bias.v" \
"../../../../lenet_stream.srcs/sources_1/imports/src/convolution.v" \
"../../../../lenet_stream.srcs/sources_1/imports/src/fc1.v" \
"../../../../lenet_stream.srcs/sources_1/imports/src/fc1_bias.v" \
"../../../../lenet_stream.srcs/sources_1/imports/src/fc1_weights.v" \
"../../../../lenet_stream.srcs/sources_1/imports/src/fc2.v" \
"../../../../lenet_stream.srcs/sources_1/imports/src/fc2_bias.v" \
"../../../../lenet_stream.srcs/sources_1/imports/src/fc2_weights.v" \
"../../../../lenet_stream.srcs/sources_1/imports/src/lineBuffer.v" \
"../../../../lenet_stream.srcs/sources_1/imports/src/maxpool.v" \
"../../../../lenet_stream.srcs/sources_1/imports/src/relu.v" \
"../../../../lenet_stream.srcs/sources_1/imports/src/weights_kernel.v" \
"../../../../lenet_stream.srcs/sim_1/imports/sim/line_buf_conv_tb.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

